### ISSUE TITLE
Feature Request: Implement secure database credentials

### ISSUE THREAD

**Issue by jasonmcboyd** [data-integrations/database-plugins#76]
# This is a feature request

The SQL Server plugin (maybe the other database plugins as well) take the credentials as plain text arguments. They also export the credentials in plain text when exporting Data Fusion pipelines. As result we cannot grant view permission to Data Fusion for anybody that is not allowed to access the password.

Ideally, privileged users would deploy the passwords in the data proc cluster (or elsewhere) and then less privileged users could access and run Data Fusion pipelines without exposing the passwords to them. I have noticed, for example, that the BigQuery plugin does this by reading the service account credentials from the nodes in the data proc cluster.

**Comment by sreevatsanraman** [comment]
To store the credentials securely, recommend using a secure store Hadoop KMS or Cloud KMS and the configurations can be accessed using secure macros. Here are the relevant docs and blog post
https://docs.cdap.io/cdap/6.2.0/en/user-guide/pipelines/creating-pipelines.html#secure-function

https://medium.com/cdapio/securely-storing-sensitive-information-and-using-it-in-cdap-6bbafa96597d
